In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/bangDataSet/cleanedBongDataSet.csv")

In [ ]:
features = [
    "Interest_Loss",
    "Feeling_Down",
    "Insomnia",
    "Fatigue_Frequency",
    "Low_Appetite",
    "Self_Perceived_Failure",
    "Difficulty_Focusing",
    "Agitation_Level",
    "Suicidal_Thoughts"
]

target = "Depression Level (CES-D) (20 items)"

X1 = df[features]
y1 = df[target]

In [ ]:
features_indirect = [
    # Lifestyle & health
    "Sleep_Duration",
    "Physical_Activity",
    "Smoking",
    "Alcohol_Consumption",
    "On_Medication",
    "Significant_Ailments",

    # Academic & workload
    "Academic Status",
    "Work_While_Study",
    "Workload_Academic_Demand",
    "Performance_Decline",

    # Social & relational
    "Relationship_Status_Single",
    "Relationship_Status_In a Relationship",
    "Relationship_Status_Married",
    "Relationship_Status_Divorced",
    "Social_Withdrawal",
    "Isolation_Frequency",
    "No_Support_Frequency",
    "Loneliness_Frequency",
    "Share_Feelings_Lack",

    # Cognitive & emotional (implicit)
    "Indecisiveness",
    "Irritability",
    "Restlessness",
    "Fear_Something_Bad",
    "Life_Feels_Hard",
    "Feeling_Insignificant",
    "Self_Confidence_Erosion"
]

target = "Depression Level (CES-D) (20 items)"

X2 = df[features_indirect]
y2 = df[target]


In [ ]:
features_indirect = [
  "Gender",
  "Relationship_Status_Divorced",
  "Relationship_Status_In a Relationship",
  "Relationship_Status_Married",
  "Relationship_Status_Single",
  "Age",
  'Academic Status',
  'Work_While_Study',
  'Residential_Area_Hall',
  'Residential_Area_With family',
  'Residential_Area_Outside Hall',
  'Social Economic Status',
  'Financial_Pressure',
  'Has_Debts',
  'Satisfied_Living_Environment',
  'Lost_Someone_Recently',
  'Physical_Activity',
  'Significant_Ailments',
  'On_Medication',
  'Smoking',
  'Alcohol_Consumption',
  'Sleep_Duration',
  'Social_Media_Hours',
  'Workload_Academic_Demand',
  'Melancholic',
  'Future_Hopelessness',
  'Self_Perceived_Failure',
  'Interest_Loss',
  'Meaninglessness',
  'Hopelessness_EndFeeling',
  'Feeling_Insignificant',
  'Self_Confidence_Erosion',
  'Suicidal_Thoughts',
  'Crying_Frequency',
  'Agitation_Level',
  'Social_Withdrawal',
  'Indecisiveness',
  'Anhedonia_No_Joy',
  'Fatigue_Frequency',
  'Insomnia',
  'Irritability',
  'Low_Appetite',
  'Difficulty_Focusing',
  'Easy_Fatigue',
  'Low_Concentration',
  'Difficulty_Speaking_Socially',
  'High_Appetite',
  'Restlessness',
  'Life_Feels_Hard',
  'Fear_Something_Bad',
  'Recent_Abuse_Experience',
  'Feels_Pitied',
  'Lack_of_Pleasure',
  'Feeling_Down',
  'Feels_Others_Are_Kind',
  'Performance_Decline',
  'Share_Feelings_Lack',
  'Social_LeftOut_Level',
  'Isolation_Frequency',
  'No_Support_Frequency',
  'Loneliness_Frequency',
  'Emotional_Alignment_Frequency',
  'Presence_Not_Genuine_Frequency',
  'Relationships_Unimportant_Level'
]

target = "Depression Level (CES-D) (20 items)"

X3 = df[features_indirect]
y3 = df[target]


In [ ]:
def train_and_evaluate(X, y, dataset_name):
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    models = {
        "Logistic Regression": Pipeline([
            ("scaler", StandardScaler()),
            ("model", LogisticRegression(max_iter=1000))
        ]),
        "Random Forest": RandomForestClassifier(
            n_estimators=200,
            random_state=42
        ),
        "SVM": Pipeline([
            ("scaler", StandardScaler()),
            ("model", SVC(kernel="rbf"))
        ])
    }

    print(f"\n===== Results for {dataset_name} =====")

    for name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        acc = accuracy_score(y_test, y_pred)
        cm = confusion_matrix(y_test, y_pred)

        print(f"\n{name}")
        print(f"Accuracy: {acc:.4f}")
        print("Confusion Matrix:")
        print(cm)


In [ ]:
import numpy as np
from scipy.stats import spearmanr
def compute_spearman_weights(X, y):
    """
    X: DataFrame of features
    y: Series target
    Returns: dict {feature: normalized_weight}
    """

    correlations = {}

    for feature in X.columns:
        corr, _ = spearmanr(X[feature], y)
        correlations[feature] = abs(corr)

    total_corr = sum(correlations.values())

    weights = {
        feature: corr / total_corr
        for feature, corr in correlations.items()
    }

    return weights


In [ ]:
weights = compute_spearman_weights(X3, y3)

for k, v in sorted(weights.items(), key=lambda x: x[1], reverse=True):
    print(f"{k}: {v:.4f}")


Self_Perceived_Failure: 0.0315
Feeling_Down: 0.0315
Melancholic: 0.0314
Anhedonia_No_Joy: 0.0313
Lack_of_Pleasure: 0.0313
Difficulty_Focusing: 0.0313
Life_Feels_Hard: 0.0306
Feeling_Insignificant: 0.0305
Future_Hopelessness: 0.0300
Self_Confidence_Erosion: 0.0294
Low_Concentration: 0.0293
Restlessness: 0.0291
Performance_Decline: 0.0290
Fatigue_Frequency: 0.0281
Interest_Loss: 0.0280
Hopelessness_EndFeeling: 0.0279
Social_Withdrawal: 0.0277
Agitation_Level: 0.0264
Indecisiveness: 0.0263
Crying_Frequency: 0.0256
Irritability: 0.0251
Feels_Pitied: 0.0249
Feels_Others_Are_Kind: 0.0249
Insomnia: 0.0216
Low_Appetite: 0.0200
Meaninglessness: 0.0189
Share_Feelings_Lack: 0.0188
Social_LeftOut_Level: 0.0181
Fear_Something_Bad: 0.0178
Isolation_Frequency: 0.0172
Relationships_Unimportant_Level: 0.0172
Emotional_Alignment_Frequency: 0.0135
No_Support_Frequency: 0.0132
Difficulty_Speaking_Socially: 0.0131
Loneliness_Frequency: 0.0113
Presence_Not_Genuine_Frequency: 0.0113
Recent_Abuse_Experience: 

In [ ]:
def apply_feature_weights(X, weights):
    X_weighted = X.copy()
    for feature in X.columns:
        X_weighted[feature] = X_weighted[feature] * weights[feature]
    return X_weighted


In [ ]:
X3_weighted = apply_feature_weights(X3, weights)


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
def train_weighted_model(X, y, dataset_name):
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    models = {
        "Weighted Logistic Regression": Pipeline([
            ("scaler", StandardScaler()),
            ("model", LogisticRegression(max_iter=1000))
        ]),
        "Weighted Random Forest": RandomForestClassifier(
            n_estimators=200,
            random_state=42
        ),
        "Weighted SVM": Pipeline([
            ("scaler", StandardScaler()),
            ("model", SVC(kernel="rbf"))
        ])
    }

    print(f"\n===== Spearman-Weighted Results for {dataset_name} =====")

    for name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        acc = accuracy_score(y_test, y_pred)
        cm = confusion_matrix(y_test, y_pred)

        print(f"\n{name}")
        print(f"Accuracy: {acc:.4f}")
        print("Confusion Matrix:")
        print(cm)


### ----OUTPUT----

In [ ]:
train_and_evaluate(X1, y1, "Direct CES-D Symptom Features (X1)")



===== Results for Direct CES-D Symptom Features (X1) =====

Logistic Regression
Accuracy: 0.8500
Confusion Matrix:
[[44  0  0  0]
 [ 3  6  4  0]
 [ 2  2 16  1]
 [ 0  1  2 19]]

Random Forest
Accuracy: 0.7900
Confusion Matrix:
[[43  1  0  0]
 [ 3  6  4  0]
 [ 3  3 12  3]
 [ 0  1  3 18]]

SVM
Accuracy: 0.8200
Confusion Matrix:
[[43  0  1  0]
 [ 1  6  6  0]
 [ 1  3 15  2]
 [ 0  1  3 18]]


In [ ]:
train_and_evaluate(X2, y2, "Indirect Behavioral Features (X2)")



===== Results for Indirect Behavioral Features (X2) =====

Logistic Regression
Accuracy: 0.7100
Confusion Matrix:
[[39  4  1  0]
 [ 6  2  5  0]
 [ 2  2 14  3]
 [ 0  0  6 16]]

Random Forest
Accuracy: 0.7500
Confusion Matrix:
[[41  2  1  0]
 [ 4  4  5  0]
 [ 3  0 14  4]
 [ 0  0  6 16]]

SVM
Accuracy: 0.7300
Confusion Matrix:
[[43  1  0  0]
 [ 5  1  7  0]
 [ 3  0 12  6]
 [ 1  0  4 17]]


In [ ]:
train_and_evaluate(X3, y3, "Complete Feature Set (X3)")



===== Results for Complete Feature Set (X3) =====

Logistic Regression
Accuracy: 0.8000
Confusion Matrix:
[[42  2  0  0]
 [ 3  6  4  0]
 [ 0  3 15  3]
 [ 0  0  5 17]]

Random Forest
Accuracy: 0.8100
Confusion Matrix:
[[43  1  0  0]
 [ 7  2  4  0]
 [ 1  0 18  2]
 [ 0  0  4 18]]

SVM
Accuracy: 0.8500
Confusion Matrix:
[[43  1  0  0]
 [ 4  3  6  0]
 [ 0  0 21  0]
 [ 0  0  4 18]]


In [ ]:
train_weighted_model(X3_weighted, y3, "CES-D with Spearman Feature Weights")



===== Spearman-Weighted Results for CES-D with Spearman Feature Weights =====

Weighted Logistic Regression
Accuracy: 0.8000
Confusion Matrix:
[[42  2  0  0]
 [ 3  6  4  0]
 [ 0  3 15  3]
 [ 0  0  5 17]]

Weighted Random Forest
Accuracy: 0.8100
Confusion Matrix:
[[43  1  0  0]
 [ 7  2  4  0]
 [ 1  0 18  2]
 [ 0  0  4 18]]

Weighted SVM
Accuracy: 0.8500
Confusion Matrix:
[[43  1  0  0]
 [ 4  3  6  0]
 [ 0  0 21  0]
 [ 0  0  4 18]]


In [ ]:
import numpy as np
import pandas as pd

from scipy.stats import spearmanr

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier

from sklearn.metrics import accuracy_score, confusion_matrix


In [ ]:
spearman_scores = {}

for feature in X3.columns:
    corr, _ = spearmanr(X3[feature], y3)
    spearman_scores[feature] = abs(corr)

# Keep top 30 most correlated features
top_features = sorted(
    spearman_scores,
    key=spearman_scores.get,
    reverse=True
)[:30]

X_selected = X3[top_features]


In [ ]:
print(X_selected.columns)

Index(['Self_Perceived_Failure', 'Feeling_Down', 'Melancholic',
       'Anhedonia_No_Joy', 'Lack_of_Pleasure', 'Difficulty_Focusing',
       'Life_Feels_Hard', 'Feeling_Insignificant', 'Future_Hopelessness',
       'Self_Confidence_Erosion', 'Low_Concentration', 'Restlessness',
       'Performance_Decline', 'Fatigue_Frequency', 'Interest_Loss',
       'Hopelessness_EndFeeling', 'Social_Withdrawal', 'Agitation_Level',
       'Indecisiveness', 'Crying_Frequency', 'Irritability', 'Feels_Pitied',
       'Feels_Others_Are_Kind', 'Insomnia', 'Low_Appetite', 'Meaninglessness',
       'Share_Feelings_Lack', 'Social_LeftOut_Level', 'Fear_Something_Bad',
       'Isolation_Frequency'],
      dtype='object')


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X_selected,
    y3,
    test_size=0.2,
    random_state=42,
    stratify=y3
)


In [ ]:
rf_param_grid = {
    "n_estimators": [300, 500],
    "max_depth": [None, 10, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}

rf_grid = GridSearchCV(
    RandomForestClassifier(random_state=42),
    rf_param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

rf_grid.fit(X_train, y_train)

best_rf = rf_grid.best_estimator_

print("Best Random Forest Parameters:")
print(rf_grid.best_params_)


Best Random Forest Parameters:
{'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 500}


In [ ]:
gb_model = GradientBoostingClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)


In [ ]:
lr_model = Pipeline([
    ("scaler", StandardScaler()),
    ("lr", LogisticRegression(max_iter=1000))
])


In [ ]:
ensemble_model = VotingClassifier(
    estimators=[
        ("lr", lr_model),
        ("rf", best_rf),
        ("gb", gb_model)
    ],
    voting="soft"
)


In [ ]:
cv_scores = cross_val_score(
    ensemble_model,
    X_selected,
    y3,
    cv=5,
    scoring="accuracy"
)

print(f"Cross-validated Consider accuracy: {cv_scores.mean():.4f}")


Cross-validated Consider accuracy: 0.8360


In [ ]:
ensemble_model.fit(X_train, y_train)

y_pred = ensemble_model.predict(X_test)

final_accuracy = accuracy_score(y_test, y_pred)
final_cm = confusion_matrix(y_test, y_pred)

print("\n===== FINAL ENSEMBLE MODEL RESULTS =====")
print(f"Test Accuracy: {final_accuracy:.4f}")
print("Confusion Matrix:")
print(final_cm)



===== FINAL ENSEMBLE MODEL RESULTS =====
Test Accuracy: 0.8400
Confusion Matrix:
[[40  4  0  0]
 [ 3  6  4  0]
 [ 0  1 19  1]
 [ 0  0  3 19]]


In [ ]:
# --- Step 1: Ensure all models are fitted ---
lr_model.fit(X_train, y_train)
gb_model.fit(X_train, y_train)
best_rf.fit(X_train, y_train)  # usually already fitted via GridSearchCV

# --- Step 2: Extract feature importances ---

# Random Forest
rf_importances = best_rf.feature_importances_
rf_feature_weights = dict(zip(top_features, rf_importances))

# Logistic Regression (average absolute coefficients across classes)
lr_coeffs = lr_model.named_steps['lr'].coef_
lr_weights = np.mean(np.abs(lr_coeffs), axis=0)
lr_feature_weights = dict(zip(top_features, lr_weights))

# Gradient Boosting
gb_importances = gb_model.feature_importances_
gb_feature_weights = dict(zip(top_features, gb_importances))

# --- Step 3: Normalize each model's importances ---
def normalize(d):
    total = sum(d.values())
    return {k: v/total for k, v in d.items()}

rf_norm = normalize(rf_feature_weights)
lr_norm = normalize(lr_feature_weights)
gb_norm = normalize(gb_feature_weights)

# --- Step 4: Compute ensemble-averaged weights ---
ensemble_weights = {f: (rf_norm[f] + lr_norm[f] + gb_norm[f]) / 3 for f in top_features}

# --- Step 5: Sort descending ---
ensemble_weights = dict(sorted(ensemble_weights.items(), key=lambda x: x[1], reverse=True))

# --- Step 6: Print nicely ---
print("Ensemble-averaged feature importances (normalized, descending):")
for f, w in ensemble_weights.items():
    print(f"{f}: {w:.4f}")


Ensemble-averaged feature importances (normalized, descending):
Self_Perceived_Failure: 0.0849
Lack_of_Pleasure: 0.0653
Feeling_Down: 0.0540
Life_Feels_Hard: 0.0524
Melancholic: 0.0517
Future_Hopelessness: 0.0509
Anhedonia_No_Joy: 0.0507
Performance_Decline: 0.0453
Difficulty_Focusing: 0.0387
Restlessness: 0.0375
Feeling_Insignificant: 0.0371
Indecisiveness: 0.0357
Hopelessness_EndFeeling: 0.0346
Insomnia: 0.0314
Crying_Frequency: 0.0295
Interest_Loss: 0.0277
Feels_Others_Are_Kind: 0.0274
Feels_Pitied: 0.0268
Irritability: 0.0247
Low_Appetite: 0.0238
Fear_Something_Bad: 0.0235
Social_Withdrawal: 0.0231
Agitation_Level: 0.0215
Share_Feelings_Lack: 0.0206
Self_Confidence_Erosion: 0.0187
Fatigue_Frequency: 0.0169
Low_Concentration: 0.0147
Social_LeftOut_Level: 0.0109
Isolation_Frequency: 0.0105
Meaninglessness: 0.0094
