In [4]:
import pandas as pd
import numpy as np
import pickle
import joblib
from pathlib import Path

from scipy.stats import spearmanr

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [5]:
df = pd.read_csv("/content/drive/MyDrive/Academic_Project/DataSet/dataProcessed.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Academic_Project/DataSet/dataProcessed.csv'

In [ ]:
# print(df.shape)
# df.head()
# for col in df:
#     print(col)
#     print(df[col].unique())

In [ ]:
TARGET_COLUMN = "Depression Level (PHQ-9 items)"

In [ ]:
X1_FEATURES = [
    "Agitation_Level",
    "Difficulty_Focusing",
    "Fatigue_Frequency",
    "Feeling_Down",
    "Insomnia",
    "Interest_Loss",
    "Low_Appetite",
    "Self_Perceived_Failure",
    "Suicidal_Thoughts"
]

In [ ]:
X2_FEATURES = [
    "Academic Status",
    "Alcohol_Consumption",
    "Fear_Something_Bad",
    "Feeling_Insignificant",
    "Indecisiveness",
    "Irritability",
    "Isolation_Frequency",
    "Life_Feels_Hard",
    "Loneliness_Frequency",
    "No_Support_Frequency",
    "On_Medication",
    "Performance_Decline",
    "Physical_Activity",
    "Relationship_Status_Divorced",
    "Relationship_Status_In a Relationship",
    "Relationship_Status_Married",
    "Relationship_Status_Single",
    "Restlessness",
    "Self_Confidence_Erosion",
    "Share_Feelings_Lack",
    "Significant_Ailments",
    "Sleep_Duration",
    "Smoking",
    "Social_Withdrawal",
    "Work_While_Study",
    "Workload_Academic_Demand"
]

In [ ]:
X3_FEATURES = [
  "Academic Status",
    "Age",
    "Agitation_Level",
    "Alcohol_Consumption",
    "Anhedonia_No_Joy",
    "Crying_Frequency",
    "Difficulty_Focusing",
    "Difficulty_Speaking_Socially",
    "Easy_Fatigue",
    "Emotional_Alignment_Frequency",
    "Fatigue_Frequency",
    "Fear_Something_Bad",
    "Feeling_Down",
    "Feeling_Insignificant",
    "Feels_Others_Are_Kind",
    "Feels_Pitied",
    "Financial_Pressure",
    "Future_Hopelessness",
    "Gender",
    "Has_Debts",
    "High_Appetite",
    "Hopelessness_EndFeeling",
    "Indecisiveness",
    "Insomnia",
    "Interest_Loss",
    "Irritability",
    "Isolation_Frequency",
    "Lack_of_Pleasure",
    "Life_Feels_Hard",
    "Loneliness_Frequency",
    "Lost_Someone_Recently",
    "Low_Appetite",
    "Low_Concentration",
    "Meaninglessness",
    "Melancholic",
    "No_Support_Frequency",
    "On_Medication",
    "Performance_Decline",
    "Physical_Activity",
    "Presence_Not_Genuine_Frequency",
    "Recent_Abuse_Experience",
    "Relationship_Status_Divorced",
    "Relationship_Status_In a Relationship",
    "Relationship_Status_Married",
    "Relationship_Status_Single",
    "Relationships_Unimportant_Level",
    "Residential_Area_Hall",
    "Residential_Area_Outside Hall",
    "Residential_Area_With family",
    "Restlessness",
    "Satisfied_Living_Environment",
    "Self_Confidence_Erosion",
    "Self_Perceived_Failure",
    "Share_Feelings_Lack",
    "Significant_Ailments",
    "Sleep_Duration",
    "Smoking",
    "Social Economic Status",
    "Social_LeftOut_Level",
    "Social_Media_Hours",
    "Social_Withdrawal",
    "Suicidal_Thoughts",
    "Work_While_Study",
    "Workload_Academic_Demand"
]

In [ ]:
X1 = df[X1_FEATURES]
X2 = df[X2_FEATURES]
X3 = df[X3_FEATURES]

y = df[TARGET_COLUMN]

In [ ]:
def get_spearman_selected_features(X, y, threshold=0.10):
    selected_features = []

    for column in X.columns:
        corr, _ = spearmanr(X[column], y)

        if abs(corr) >= threshold:
            selected_features.append(column)

    return selected_features

In [ ]:
X4_FEATURES = get_spearman_selected_features(X3, y)

print("Selected Features:")
print(X4_FEATURES)

Selected Features:
['Agitation_Level', 'Anhedonia_No_Joy', 'Crying_Frequency', 'Difficulty_Focusing', 'Difficulty_Speaking_Socially', 'Easy_Fatigue', 'Emotional_Alignment_Frequency', 'Fatigue_Frequency', 'Fear_Something_Bad', 'Feeling_Down', 'Feeling_Insignificant', 'Feels_Others_Are_Kind', 'Feels_Pitied', 'Financial_Pressure', 'Future_Hopelessness', 'Has_Debts', 'High_Appetite', 'Hopelessness_EndFeeling', 'Indecisiveness', 'Insomnia', 'Interest_Loss', 'Irritability', 'Isolation_Frequency', 'Lack_of_Pleasure', 'Life_Feels_Hard', 'Loneliness_Frequency', 'Lost_Someone_Recently', 'Low_Appetite', 'Low_Concentration', 'Meaninglessness', 'Melancholic', 'No_Support_Frequency', 'On_Medication', 'Performance_Decline', 'Presence_Not_Genuine_Frequency', 'Recent_Abuse_Experience', 'Relationships_Unimportant_Level', 'Restlessness', 'Satisfied_Living_Environment', 'Self_Confidence_Erosion', 'Self_Perceived_Failure', 'Share_Feelings_Lack', 'Significant_Ailments', 'Sleep_Duration', 'Social Economic St

In [ ]:
X4 = X3[X4_FEATURES]

###Saving Features

In [ ]:
def save_dataframe_as_list(df_data, filename):
    data_list = df_data.values.tolist()

    joblib.dump(data_list, filename)

    print(f"Saved: {filename}")

In [ ]:
save_dataframe_as_list(X1, "/content/drive/MyDrive/academic_saved/feature_structure/x1_phq9.pkl")
save_dataframe_as_list(X2, "/content/drive/MyDrive/academic_saved/feature_structure/x2_phq9.pkl")
save_dataframe_as_list(X3, "/content/drive/MyDrive/academic_saved/feature_structure/x3_phq9.pkl")
save_dataframe_as_list(X4, "/content/drive/MyDrive/academic_saved/feature_structure/x4_phq9.pkl")

Saved: /content/drive/MyDrive/academic_saved/feature_structure/x1_phq9.pkl
Saved: /content/drive/MyDrive/academic_saved/feature_structure/x2_phq9.pkl
Saved: /content/drive/MyDrive/academic_saved/feature_structure/x3_phq9.pkl
Saved: /content/drive/MyDrive/academic_saved/feature_structure/x4_phq9.pkl


###Model Training

In [ ]:
BASE_DIR = Path(
    "/content/drive/MyDrive/academic_saved/model_outputs"
)

BASE_DIR.mkdir(parents=True, exist_ok=True)

OUTPUT_FILE = BASE_DIR / "PHQ-9_all_models_output.txt"
CONFUSION_FILE = BASE_DIR / "PHQ-9_all_models_confusion_matrix.txt"

In [ ]:
with open(OUTPUT_FILE, "w") as f:
    f.write("PHQ-9 MODEL TRAINING OUTPUTS\n")
    f.write("=" * 80 + "\n\n")

with open(CONFUSION_FILE, "w") as f:
    f.write("PHQ-9 CONFUSION MATRICES\n")
    f.write("=" * 80 + "\n\n")

In [ ]:
def train_and_save_model(
    model,
    model_name,
    feature_set_name,
    X,
    y
):

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("model", model)
    ])

    # TRAIN
    pipeline.fit(X_train, y_train)

    # PREDICT
    y_pred = pipeline.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)

    report = classification_report(y_test, y_pred)

    cm = confusion_matrix(y_test, y_pred)


    # CONSOLE OUTPUT
    output_text = (
        f"{'=' * 60}\n"
        f"Model: {model_name}\n"
        f"Feature Set: {feature_set_name}\n"
        f"Accuracy: {accuracy:.4f}\n\n"
        f"Classification Report:\n"
        f"{report}\n"
    )

    print(output_text)


    # SAVE TRAINING OUTPUT
    with open(OUTPUT_FILE, "a", encoding="utf-8") as file:
        file.write(output_text)
        file.write("\n")


    # CONFUSION MATRIX OUTPUT
    confusion_text = (
        f"{'=' * 60}\n"
        f"Model: {model_name}\n"
        f"Feature Set: {feature_set_name}\n\n"
        f"Confusion Matrix:\n"
        f"{cm}\n\n"
    )

    print(confusion_text)


    # SAVE CONFUSION MATRIX
    with open(CONFUSION_FILE, "a", encoding="utf-8") as file:
        file.write(confusion_text)
        file.write("\n")

    save_dir = (
        "/content/drive/MyDrive/academic_saved/trained_models"
    )

    # MODEL FILE NAME
    filename = (
        f"{save_dir}/"
        f"{model_name.lower().replace(' ', '_')}_"
        f"{feature_set_name.lower().replace(' ', '_')}_"
        f"phq9.pkl"
    )

    # SAVE MODEL
    joblib.dump(pipeline, filename)

    print(f"Saved Model: {filename}")

In [ ]:
models = {
    "logistic_regression": LogisticRegression(max_iter=1000),

    "random_forest": RandomForestClassifier(
        n_estimators=200,
        random_state=42
    ),

    "svm": SVC(kernel="rbf")
}

In [ ]:
feature_sets = {
    "x1": X1,
    "x2": X2,
    "x3": X3,
    "x4": X4
}

In [ ]:
for model_name, model in models.items():

    for feature_name, feature_data in feature_sets.items():

        train_and_save_model(
            model=model,
            model_name=model_name,
            feature_set_name=feature_name,
            X=feature_data,
            y=y
        )

Model: logistic_regression
Feature Set: x1
Accuracy: 0.7800

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.81      0.85        21
           1       0.73      0.87      0.79        31
           2       0.67      0.57      0.62        21
           3       0.69      0.64      0.67        14
           4       1.00      1.00      1.00        13

    accuracy                           0.78       100
   macro avg       0.80      0.78      0.79       100
weighted avg       0.78      0.78      0.78       100


Model: logistic_regression
Feature Set: x1

Confusion Matrix:
[[17  4  0  0  0]
 [ 2 27  2  0  0]
 [ 0  5 12  4  0]
 [ 0  1  4  9  0]
 [ 0  0  0  0 13]]


Saved Model: /content/drive/MyDrive/academic_saved/trained_models/logistic_regression_x1_phq9.pkl
Model: logistic_regression
Feature Set: x2
Accuracy: 0.5500

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.71 